---
title: "Vegetation Indices from Satellite Images"
description: |
  Calculating vegetation indices from remotely sensed data using Google Earth Engine in R
author:
  - name: Abhishek Kumar
    url: https://akumar.netlify.app
date: 08-22-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```



```{r rgee-setup, eval=FALSE}
## install the package rgee
install.packages("rgee")

## load the package
library(rgee)

## initially run once to set up rgee
ee_install(py_env = "rgee")

## check for proper set up for rgee installation and dependencies
ee_check() # Check non-R dependencies
ee_clean_credentials() # Remove credentials of a specific user
ee_clean_pyenv() # Remove reticulate system variables

## Initialize Earth Engine!
ee_Initialize()

srtm <- ee$Image("USGS/SRTMGL1_003") 
```

# Extract climate data from TerraClimate

```{r}
library(rgee)
library(sf)
library(tidyverse)

ee_Initialize()

## read the boundary for MHWLS (area of interest)
mwls <- st_read("data/pas.gpkg") |> filter(short_name == "MH") |> sf_as_ee()

## Map each image from 2019 to extract the monthly precipitation (Pr)
terraclimate <- ee$ImageCollection("IDAHO_EPSCOR/TERRACLIMATE") |>
  
  ## filter date
  ee$ImageCollection$filterDate("2019-01-01", "2020-01-01") |>
  
  ## Select only precipitation bands
  ee$ImageCollection$map(function(x) x$select("pr")) |> 
  
  ## from imagecollection to image
  ee$ImageCollection$toBands() |> 
  
  ## rename the bands of an image
  ee$Image$rename(sprintf("PP_%02d", 1:12))

## extract precipitation values for area of interest
ee_mwls_rain <- ee_extract(x = terraclimate, y = mwls, sf = FALSE)


ee_mwls_rain |>
  pivot_longer(-c(1:6), names_to = "month", values_to = "pr") |>
  mutate(month, month = gsub("PP_", "", month)) |>
  ggplot(aes(x = month, y = pr, group = name, color = pr)) +
  geom_line(alpha = 0.4, lwd = 2.5) +
  xlab("Month") +
  ylab("Precipitation (mm)") +
  theme_minimal()
```

# Create an NDVI-animation

```{r eval=FALSE}
library(magick)

## Define the regional bounds of animation frames and a mask to clip the NDVI data by.
mwls <- st_read("data/pas.gpkg") |> filter(short_name == "MH") |> sf_as_ee()
region <- mwls$geometry()$bounds()

## Retrieve the MODIS Terra Vegetation Indices 16-Day Global 1km dataset as 
## an ee.ImageCollection and select the NDVI band.
col <- ee$ImageCollection('MODIS/006/MOD13A2')$select('NDVI')

## Group images by composite date
col <- col$map(function(img) {
  doy <- ee$Date(img$get('system:time_start'))$getRelative('day', 'year')
  img$set('doy', doy)
})
distinctDOY <- col$filterDate('2013-01-01', '2014-01-01')

## Define a filter that identifies which images from the complete collection
## match the DOY from the distinct DOY collection.
filter <- ee$Filter$equals(leftField = 'doy', rightField = 'doy')

## Define a join; convert the resulting FeatureCollection to an ImageCollection.
join <- ee$Join$saveAll('doy_matches')
joinCol <- ee$ImageCollection(join$apply(distinctDOY, col, filter))


## Apply median reduction among matching DOY collections.
comp <- joinCol$map(function(img) {
  doyCol = ee$ImageCollection$fromImages(
    img$get('doy_matches')
  )
  doyCol$reduce(ee$Reducer$median())
})

## Define RGB visualization parameters.
visParams = list(
  min = 0.0,
  max = 9000.0,
  bands = "NDVI_median",
  palette = c(
    'FFFFFF', 'CE7E45', 'DF923D', 'F1B555', 'FCD163', '99B718', '74A901',
    '66A000', '529400', '3E8601', '207401', '056201', '004C00', '023B01',
    '012E01', '011D01', '011301'
  )
)

## Create RGB visualization images for use as animation frames.
rgbVis <- comp$map(function(img) {
  do.call(img$visualize, visParams) |>
    ee$Image$clip(mwls)
})

## Define GIF visualization parameters.
gifParams <- list(
  region = region,
  dimensions = 600,
  crs = 'EPSG:4326',
  framesPerSecond = 10
)

## Get month names
dates_modis_mabbr <- distinctDOY |>
  ee_get_date_ic() |> # Get Image Collection dates
  select(time_start) |> # Select time_start column
  # Get the month component of the datetime
  mutate(month = lubridate::month(as.POSIXlt(x = time_start, format="%Y-%m-%d"))) |> 
  mutate(months = month.abb[month]) |>
  select(months)

## Use ee_utils_gif_* functions to render the GIF animation and add some texts.
ee_utils_creat

animation <- ee_utils_gif_creator(rgbVis, gifParams, mode = "wb")
animation |>
  ee_utils_gif_annotate(
    text = "NDVI: MODIS/006/MOD13A2",
    size = 15, color = "white",
    location = "+10+10"
  ) |>
  ee_utils_gif_annotate(
    text = dates_modis_mabbr,
    size = 30,
    location = "+290+350",
    color = "white",
    font = "arial",
    boxcolor = "#000000"
  ) # -> animation_wtxt

#ee_utils_gif_save(animation_wtxt, path = "raster_as_ee.gif")

print(rgbVis.getVideoThumbURL(gifParams));
```

