---
title: "3d map with satellite"
description: |
  A short description of the post.
author:
  - name: Abhishek Kumar
    url: https://akumar.netlify.app
date: 08-11-2021
output:
  distill::distill_article:
    self_contained: false
---


# load the packages

```{r}
library(rayshader)
library(sp)
library(raster)
library(scales)
```


```{r}
morni_elev <- raster("D:/spatial-data/dem/n30_e076_1arc_v3.tif") |> 
  merge(raster("D:/spatial-data/dem/n30_e077_1arc_v3.tif")) |>
  crop(extent(76.8764, 77.0085, 30.6239, 30.7560))

raster_to_matrix(morni_elev) |> height_shade() |> 
  plot_map()
```

```{r}
filepath <- "D:/spatial-data/landsat/LC08_L1TP_147039_20210627_20210707_01_T1/LC08_L1TP_147039_20210627_20210707_01_T1_B"
mred <- raster(paste0(filepath, 4, ".TIF"))
mgreen <- raster(paste0(filepath, 3, ".TIF"))
mblue <- raster(paste0(filepath, 2, ".TIF"))

morni_rbg <- raster::stack(mred, mgreen, mblue)
raster::plotRGB(morni_rbg, scale=255^2)
```

```{r}
morni_elev_utm <- raster::projectRaster(morni_elev, crs = crs(mred), method = "bilinear")

bottom_left <- c(y=76.8, x=30.66)
top_right   <- c(y=77, x=30.8)

extent_latlong = sp::SpatialPoints(rbind(bottom_left, top_right), proj4string=sp::CRS("+proj=longlat +ellps=WGS84 +datum=WGS84"))
extent_utm = sp::spTransform(extent_latlong, raster::crs(zion_elevation_utm))

e = raster::extent(extent_utm)
e
```


```{r}
#76.8, 77.1, 30.6, 30.9
# define a bounding box for area of interest
osm_bbox <- c(76.8, 30.6, 77.1, 30.9) # xmin, ymin, xmax, ymax

# extract boundaries for pas
#dem_pas <- opq(osm_bbox) |> 
  #add_osm_feature(key = "boundary", value = "protected_area", value_exact = F) |> 
  #osmdata_sf()
#pas <- dem_pas$osm_polygons |> mutate(short_name = c("MH", "BS", "SL"))
#st_write(pas, "data/pas.gpkg")
```

```{r}
"D:\spatial-data\landsat\LC08_L1TP_147039_20210627_20210707_01_T1\LC08_L1TP_147039_20210627_20210707_01_T1_B2.TIF"
```

