---
name: "modis-vegetation"
title: "Patterns and drivers of Vegetation Change in Morni Hills (Haryana), India"
description: |
  A short description of the post.
author:
  - name: Abhishek Kumar
    url: https://akumar.netlify.app
date: 2022-01-09
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, comment = "#>",
                      warning = F, message = F,
                      dev = "svglite")
```


## Abstract


## Introduction


## Methodology

### Study area

### Data

* https://lpdaac.usgs.gov/products/mod13q1v006/
* Didan, K. (2015). MOD13Q1 MODIS/Terra Vegetation Indices 16-Day L3 Global 250m SIN Grid V006 [Data set]. NASA EOSDIS Land Processes DAAC. Accessed 2022-01-14 from https://doi.org/10.5067/MODIS/MOD13Q1.006


```{r eval=FALSE}
## Load the package rgee
library(rgee)

## Initialize rgee with drive
ee_Initialize(user = "abhikumarpu", drive = T)

## load the area of interest and convert to ee object
mwls <- sf::st_read("data/mwls.gpkg", quiet = T) |>
  sf_as_ee()

## MODIS Terra 16 day 250 m EVI
modis_evi <- ee$ImageCollection("MODIS/006/MOD13Q1") |>
  
  ## filter bounds
  ee$ImageCollection$filterBounds(mwls) |>
  
  ## filter dates
  ee$ImageCollection$filterDate("2000-01-01", "2022-01-01") |>
  
  ## select the EVI band
  ee$ImageCollection$select("EVI") |>
  
  ## multiply scaling factor and copy dates
  ee$ImageCollection$map(
    function(img){
      return(
        img$multiply(0.0001)$clip(mwls)
      )
    }
  )


ic_drive_files <- ee_imagecollection_to_local(
  ic = modis_evi,
  region = mwls$geometry(),
  dsn = file.path("D:/spatial-data/modis/evi", "EVI_"),
  via = "drive",
  container = "modis",
  scale = 250,
  maxPixels = 1e+09,
  lazy = TRUE,
  public = TRUE,
  add_metadata = TRUE,
  timePrefix = FALSE,
  quiet = FALSE
)

```

### Statistical analysis

```{r}
library(terra)

evi <- list.files(path = "D:/spatial-data/modis/terra-16day-250m-evi-mwls-2000-2021",
           pattern = ".tif$",
           full.names = T) |> 
  rast()

evi
```

## Results





## Discussion


